package GUI;

import Logica.Jugador;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class ConectarYUnirse extends javax.swing.JPanel {

    AccionesGUI Acciones;
    
    public ConectarYUnirse(AccionesGUI Acciones) {
        initComponents();
        this.setBackground(Color.BLACK);
        this.setMinimumSize(new Dimension(485, 523));
        
        DefaultListModel  lista = new DefaultListModel();
        listJugadores.setModel(lista);
        
        this.Acciones = Acciones;
    }

    public void RefreshGameAvailability(Jugador creator, Jugador[] players, boolean GameCreated, boolean alreadyConected){
                
            DefaultListModel  lista = new DefaultListModel();
            
            if(creator == null || players == null || !GameCreated){
                btnCrearPartida.setEnabled(true);
                
            }else{
                for (Jugador player : players) {
                    lista.addElement(player.Nombre);
                }
                btnCrearPartida.setEnabled(false);                
            }  
            
            if(alreadyConected){
                btnCrearPartida.setEnabled(false);
                BtnUnirseAPartida.setEnabled(false);
                Acciones.openTablerito();
            }
            
            listJugadores.setModel(lista);
   }
    
   public void getGameAvailability(){
       Acciones.requestGameAvailable();
   }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearPartida = new javax.swing.JButton();
        BtnUnirseAPartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJugadores = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(666, 416));
        setMinimumSize(new java.awt.Dimension(666, 416));

        btnCrearPartida.setText("Crear Partida");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });

        BtnUnirseAPartida.setText("Unirse a Partida");
        BtnUnirseAPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUnirseAPartidaActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Partida Encontrada:");

        listJugadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listJugadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnUnirseAPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel1)))
                    .addComponent(btnCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnCrearPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnUnirseAPartida)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed

        Acciones.openIniciarJuego();
        
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void BtnUnirseAPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUnirseAPartidaActionPerformed
        Jugador player = new Jugador();
						
        player.Nombre = JOptionPane.showInputDialog("Ingresa tu nombre");
        
		while (player.Nombre.equals("")) {			
			player.Nombre = JOptionPane.showInputDialog("Ingresa tu nombre");
		}		
		
        Acciones.JoinGame(player);        
    }//GEN-LAST:event_BtnUnirseAPartidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnUnirseAPartida;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listJugadores;
    // End of variables declaration//GEN-END:variables
}
