package GUI;

import Logica.GameState;
import Logica.Jugador;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.ImageIcon;

public class Tablerito extends javax.swing.JFrame {

	AccionesGUI Acciones;
	TableroUI tab;

	GameState state;
	Jugador ClientPlayer;

	public Tablerito(AccionesGUI Acciones) {
		//this.cantidadAPag = cantidadApag;
		//this.players = players;
		initComponents();

		this.Acciones = Acciones;

		TableroUI t = new TableroUI(fichas());
		t.setBounds(250, 150, 500, 470);
		this.add(t);
		tab = t;
		SetUserImage();

	}

	// Manejar Juego GUI
	public void RefreshGameState(GameState state, Jugador ClientPlayer) {
		this.state = state;
		this.ClientPlayer = ClientPlayer;

		setPlayersInfo();
		tab.Refresh(state);
	}

	private void SetUserImage() {
		ImageIcon usuario1 = new ImageIcon(getClass().getResource("/imagen/Usuario.png"));
		ImageIcon tamaño1 = new ImageIcon(usuario1.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
		jLabel2.setIcon(tamaño1);

		ImageIcon usuario2 = new ImageIcon(getClass().getResource("/imagen/Usuario.png"));
		ImageIcon tamaño2 = new ImageIcon(usuario1.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_DEFAULT));
		jLabel5.setIcon(tamaño1);

		ImageIcon usuario3 = new ImageIcon(getClass().getResource("/imagen/Usuario.png"));
		ImageIcon tamaño3 = new ImageIcon(usuario1.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_DEFAULT));
		jLabel3.setIcon(tamaño1);

		ImageIcon usuario4 = new ImageIcon(getClass().getResource("/imagen/Usuario.png"));
		ImageIcon tamaño4 = new ImageIcon(usuario1.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_DEFAULT));
		jLabel4.setIcon(tamaño1);
	}

	private void setPlayersInfo() {
		if (state.players.length >= 1) {
			lblJugador1.setText(state.players[0].Nombre);
			lblMonto1.setText(state.players[0].cantidad + "");
			lblMonto1.setText("Monto del jugador: "+(state.players[0].cantidad+""));
			lblFichasJuego1.setText("Fichas en juego: "+(state.players[0].getFichasEnTablero().length + ""));
			lblFichasSinJugar1.setText("Fichas sin jugar: "+(state.players[0].getFichasDisponibles().length + ""));
			
		}

		if (state.players.length >= 2) {
			lblJugador2.setText(state.players[1].Nombre);
			lblMonto2.setText(state.players[1].cantidad + "");
			lblMonto2.setText("Monto del jugador: "+(state.players[1].cantidad+""));
			lblFichasJuego2.setText("Fichas en juego: "+(state.players[1].getFichasEnTablero().length + ""));
			lblFichasSinJugar2.setText("Fichas sin jugar: "+(state.players[1].getFichasDisponibles().length + ""));
		}

		if (state.players.length >= 3) {
			lblJugador3.setText(state.players[2].Nombre);
			lblMonto3.setText(state.players[2].cantidad + "");
			lblMonto3.setText("Monto del jugador: "+(state.players[2].cantidad+""));
			lblFichasJuego3.setText("Fichas en juego: "+(state.players[2].getFichasEnTablero().length + ""));
			lblFichasSinJugar3.setText("Fichas sin jugar: "+(state.players[2].getFichasDisponibles().length + ""));
		}

		if (state.players.length >= 4) {
			lblJugador4.setText(state.players[3].Nombre);
			lblMonto4.setText(state.players[3].cantidad + "");
			lblMonto4.setText("Monto del jugador: "+(state.players[3].cantidad+""));
			lblFichasJuego4.setText("Fichas en juego: "+(state.players[3].getFichasEnTablero().length + ""));
			lblFichasSinJugar4.setText("Fichas sin jugar: "+(state.players[3].getFichasDisponibles().length + ""));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();
        lblMonto1 = new javax.swing.JLabel();
        lblMonto2 = new javax.swing.JLabel();
        lblMonto3 = new javax.swing.JLabel();
        lblMonto4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFichasJuego1 = new javax.swing.JLabel();
        lblFichasSinJugar1 = new javax.swing.JLabel();
        lblBanco = new javax.swing.JLabel();
        lblFichasJuego2 = new javax.swing.JLabel();
        lblFichasSinJugar2 = new javax.swing.JLabel();
        lblFichasJuego3 = new javax.swing.JLabel();
        lblFichasSinJugar3 = new javax.swing.JLabel();
        lblFichasJuego4 = new javax.swing.JLabel();
        lblFichasSinJugar4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblJugador1.setText("Jugador1");

        lblJugador2.setText("Jugador2");

        lblJugador3.setText("Jugador3");

        lblJugador4.setText("Jugador4");

        lblMonto1.setText("Monto del jugador 1:");

        lblMonto2.setText("Monto del jugador 2:");

        lblMonto3.setText("M:onto del jugador 3:");

        lblMonto4.setText("Monto del jugador 4:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        lblFichasJuego1.setText("Fichas en juego:");

        lblFichasSinJugar1.setText("Fichas sin jugar:");

        lblBanco.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblBanco.setText("Banco:");

        lblFichasJuego2.setText("Fichas en juego:");

        lblFichasSinJugar2.setText("Fichas sin jugar:");

        lblFichasJuego3.setText("Fichas en juego:");

        lblFichasSinJugar3.setText("Fichas sin jugar:");

        lblFichasJuego4.setText("Fichas en juego:");

        lblFichasSinJugar4.setText("Fichas sin jugar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblJugador3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblMonto1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                            .addComponent(lblFichasJuego1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblFichasSinJugar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(598, 598, 598)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblFichasJuego2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 6, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFichasSinJugar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(31, 31, 31))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFichasSinJugar3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMonto3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFichasJuego3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185)
                                .addComponent(lblBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblFichasSinJugar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMonto4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFichasJuego4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJugador2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFichasJuego2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFichasSinJugar2)
                        .addGap(355, 355, 355)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJugador4)
                            .addComponent(lblJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMonto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFichasJuego1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFichasSinJugar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonto3)
                    .addComponent(lblMonto4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFichasJuego4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFichasSinJugar4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFichasJuego3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFichasSinJugar3)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
		Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
		StringSelection elString = new StringSelection(evt.getX() + ", " + evt.getY());
		clip.setContents(elString, null);
		System.out.println("a.addPoint(" + evt.getX() + "," + evt.getY() + ");");

    }//GEN-LAST:event_formMouseClicked

	public int[][] fichas() {
		int ox = 282;
		int oy = 156;
		int fich[][] = new int[][]{{314, 573}, {337, 551}, {355, 535}, {370, 520}, {393, 499}, {420, 472}, {448, 444}, {473, 418}, {498, 393}, {520, 417}, {548, 445}, {574, 471}, {600, 498}, {627, 520}, {638, 539}, {656, 554},
		{682, 573}, {701, 554}, {680, 528}, {665, 510}, {648, 497}, {625, 475}, {600, 448}, {571, 421}, {544, 393}, {521, 370}, {545, 345}, {572, 319}, {599, 291}, {625, 265}, {650, 240}, {673, 227}, {684, 208}, {703, 184},
		{680, 165}, {660, 185}, {642, 195}, {629, 215}, {603, 240}, {575, 268}, {548, 295}, {520, 322}, {497, 345}, {475, 324}, {449, 297}, {422, 270}, {393, 242}, {368, 218}, {353, 197}, {336, 185}, {315, 166}, {292, 185},
		{313, 206}, {325, 225}, {344, 239}, {368, 263}, {395, 291}, {423, 318}, {449, 345}, {473, 370}, {450, 393}, {423, 420}, {396, 446}, {368, 474}, {346, 499}, {327, 508}, {314, 530}, {291, 554}};

		for (int i = 0; i < fich.length; i++) {
			fich[i][0] -= ox;
			fich[i][1] -= oy;
		}

		return fich;
	}

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblFichasJuego1;
    private javax.swing.JLabel lblFichasJuego2;
    private javax.swing.JLabel lblFichasJuego3;
    private javax.swing.JLabel lblFichasJuego4;
    private javax.swing.JLabel lblFichasSinJugar1;
    private javax.swing.JLabel lblFichasSinJugar2;
    private javax.swing.JLabel lblFichasSinJugar3;
    private javax.swing.JLabel lblFichasSinJugar4;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    private javax.swing.JLabel lblMonto1;
    private javax.swing.JLabel lblMonto2;
    private javax.swing.JLabel lblMonto3;
    private javax.swing.JLabel lblMonto4;
    // End of variables declaration//GEN-END:variables
}
